config/routes.rb
Rails.application.routes.draw do
  
  root to: 'welcome#index'
  get 'about' => 'welcome#about'
  
  resources :charges, only: [:new, :create]
  resources :wikis
  resources :collaborators
  
  get 'memberships/downgrade' => 'memberships#downgrade', as: :downgrade
  get '/transfer_owner', to: 'wikis#transfer_owner', as: :transfer_owner

  devise_for :users
    
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  
  scope :visible_to, -> (user) { (user.role == 'premium') || (user.role == 'admin') ? all : where(private: false) }
  
  def private?
    self.private == true
  end
  
  def public?
    self.private == false
  end
  
  def markdown_body
    render_as_markdown(self.body)
  end
  
  def render_as_markdown(markdown)
    renderer = Redcarpet::Render::HTML.new
    extenstions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extenstions)
    (redcarpet.render markdown).html_safe
  end
  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  # Enable will_paginate to work with database queries as well as static arrays (the return of policy_scope(Wiki) below)
  require 'will_paginate/array'
  
  def index
    if current_user 
      # current user exists, apply policy scope for viewing wikis
      @wikis = policy_scope(Wiki).paginate(page: params[:page], per_page: 10)
      # @wikis = Wiki.where( user: current_user ).paginate(page: params[:page], per_page: 10)
    else
      # no user exists, supply one for viewing non-private wikis
      @user = User.new(role: 'standard')
      @wikis = Wiki.visible_to(@user).paginate(page: params[:page], per_page: 10)
      authorize @wikis
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
    @users = User.all
    authorize @wiki
    
  rescue
    # If the wiki doesn't exist...
    flash[:alert] = "Sorry... either you don't have permission to view that wiki, or it doesn't exist."
    redirect_to root_path    
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end
  
  def create
    @wiki = current_user.wikis.build(wiki_params)
    @wiki.user = current_user
    @wiki.update_attributes(updated_by: current_user.name)
    # set default privacy setting to false to account for standard users
    if @wiki.private.nil? then @wiki.private = false end
    authorize @wiki
    
    if @wiki.save
      # flash[:notice] = save_message
      redirect_to @wiki
    else
      flash[:error] = "There was an error creating your wiki."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
    @collaborators = Collaborator.all
    @collaborator = Collaborator.new
    authorize @wiki
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    @wiki.update_attributes(wiki_params)
    @wiki.update_attributes(updated_by: current_user.name)
    authorize @wiki
    
    if @wiki.save
      # flash[:notice] = save_message
      redirect_to @wiki
    else
      flash[:error] = "There was an error updating your wiki."
      render :edit
    end
  end
  
  def destroy
    @wiki = Wiki.find(params[:id])
    title = @wiki.title
    authorize @wiki
    
    if @wiki.destroy
      flash[:notice] = "\'#{title}\' deleted."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error deleting the wiki."
      render :show
    end
  end
    
  def transfer_owner
    # transfer ownership to a collaborator
    # set vars
    wiki_to_update = Wiki.find(params.require(:wiki))
    collaborator_to_remove = Collaborator.find(params.require(:collaborator))
    new_owner = User.find_by_name( collaborator_to_remove.name )
    
    # the new owner of the wiki must be a premium account member or an admin
    if new_owner.premium? || new_owner.admin?
      # set new owner
      wiki_to_update.update_attributes(user: new_owner)

      # create new collaborator with previous owner
      @collaborator = Collaborator.new(wiki_id: wiki_to_update.id, name: current_user.name, user: current_user)
      @collaborator.save

      # remove old collaborator
      collaborator_to_remove.destroy

      # let the user know xfer completed
      flash[:notice] = "Ownership transferred to #{new_owner.name}. You are now set as a collaborator."
    else
      # alert as to why cannot xfer ownership
      flash[:alert] = "Cannot transfer ownership to #{new_owner.name}. Only Premium Account members can take ownership of private wikis."
    end
    redirect_to edit_wiki_path(wiki_to_update)
  end
  
  private
  
  def wiki_params
    params.require(:wiki).permit(:title, :subtitle, :body, :private)
  end
    
  def save_message
    @wiki.private == true ? 'Wiki saved as private.' : 'Wiki saved!'
  end
  
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_collaborators.html.erb
<p><strong>Collaborators</strong></p>

<% if @wiki.user == current_user %>
  <small class="nudge-up-10">Type the name of the user to add. Remove users with <span class="glyphicon glyphicon-remove-circle text-dark-gray"></span>. Transfer ownership with <span class="glyphicon glyphicon-transfer text-dark-gray"></span>.</small>
  <!-- <small class="nudge-up-10">Type the name of the user to add.</small> -->

  <%= form_for collaborator do |f| %>
    <%= f.hidden_field :wiki_id, value: wiki.id %>
    <%= f.text_field :name, class: "form-control nudge-up-5" %>
    <%= f.submit "Add", class: "btn btn-default" %>
  <% end %>

  <div class="list-group">
    <ul class="list-group-item no-bullets nudge-down-5">

      <% wiki.collaborators.each do |collaborator| %>
        <li>
          <%= collaborator.name %>
          <%= link_to "", transfer_owner_path(wiki: wiki, collaborator: collaborator), class: "glyphicon glyphicon-transfer text-dark-gray", data: { confirm: "Are you sure you want to transfer ownership to #{collaborator.name}?" } %>
          <%= link_to "", [collaborator], method: :delete, class: "glyphicon glyphicon-remove-circle text-dark-gray", data: { confirm: "Are you sure you want to remove #{collaborator.name} as a collaborator?" } %>
        </li>
      <% end %>

    </ul>
  </div>

<% else %>
  <div class="no-bullets">
    <% @wiki.collaborators.each do |collaborator| %>
      <li class="<%= bold_if_current_user(collaborator) %>">
        <%= collaborator.name %>
      </li>
    <% end %>
  </div>

<% end %>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 12, class: 'form-control' %>
    <!-- <div id="epiceditor"> -- f.hidden_field :body, id: "body" -- </div> -->
  </div>

  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox nudge-right-20' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-default' %>
  </div>

  <!-- epic editor -->

  <script>
    var editor = new EpicEditor().load();
    var showEditor = (editor.getElement('editor').body.innerHTML = '<%= escape_javascript(@wiki.body) %>');
    function prep() {
      $("#body")[0].value = showEditor;
    }
  </script>
<% end %>

app/views/wikis/edit.html.erb
<div class="row">
  <div class="col-md-9 col-sm-9 col-xs-9 border-lightgrey-right">

    <h1>Edit Wiki</h1>
    
    <%= render partial: "form", locals: { wiki: @wiki } %>
    
  </div>
  <div class="col-md-3 col-sm-3 col-xs-3 ">
    <br/>
    
    <% if @wiki.private? %>
      <%= render partial: "collaborators", locals: { users: @users, collaborator: @collaborator, collaborators: @collaborators, wiki: @wiki } %>
    <% else %>
      <h4>This wiki can be edited by everyone!</h4>
    <% if (@wiki.user == current_user) && (current_user.standard?) %>
        <h5>Make this wiki exclusive to only you and your collaborators by upgrading to a Premium Account!</h5>
        <%= link_to "Upgrade now!", new_charge_path, class: 'btn btn-primary' %>
      <% end %>
    <%end %>
    
    
  </div>
</div>

app/views/wikis/index.html.erb
<h1>
  All Wikis
  <% if policy(Wiki.new).create? %>
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-default nudge-up-5' %>
  <% end %>
</h1>

<div class="pull-right nudge-down-10">
  <%= will_paginate @wikis %>
</div>

<br/><br/>

<% @wikis.each do |wiki| %>
  <div class="highlighter-gray wiki-index-display">
    <h4>
      <%= link_to wiki.title, wiki_path(wiki) %>
      <span class="badge nudge-up-3"><%= wiki.private? ? 'Private' : '' %></span>
    </h4>
    <small class="nudge-up-10"><%= wiki.subtitle %></small>
    <br/>
    <small class="nudge-up-12 text-dark-gray"><i>Created <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.name %> | Updated <%= time_ago_in_words(wiki.updated_at) %> ago by <%= wiki.updated_by %></i></small>
  </div>
<% end %>

<%= will_paginate @wikis %>

<br/><br/>

app/views/wikis/new.html.erb
<div class="row">
  <div class="col-md-9 col-sm-9 col-xs-9 border-lightgrey-right">

    <h1>New Wiki</h1>
    
    <%= render partial: "form", locals: { wiki: @wiki } %>
    
  </div>
  <div class="col-md-3 col-sm-3 col-xs-3 ">
    <br/>
    
    <% if current_user.standard? %>
      <p>Want to make this wiki private? Upgrade to a <b>Premium Account</b>, and you'll also be able to designate who gets to see and edit your wikis.</p>
      <%= link_to "Upgrade now!", edit_user_registration_path(current_user), class: 'btn btn-primary' %>
    <% else %>
      <p>Writer's block? Need inspiration?</p>
      <%= link_to "Consult an oracle", "http://www.google.com", target: "_blank", class: 'btn btn-default' %>
    <% end %>
    
  </div>
</div>

app/views/wikis/show.html.erb
<div class="row">
  <div class="col-md-9 col-sm-9 col-xs-9 border-lightgrey-right">

    <h1>
      <%= @wiki.title %>
      <span class="badge nudge-up-5"><%= @wiki.private? ? 'Private' : '' %></span>
    </h1>
    <h3><%= @wiki.subtitle %></h3>
    <small>
      Created <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.name %> | 
      Updated <%= time_ago_in_words(@wiki.updated_at) %> ago by <%= @wiki.updated_by %>
    </small>

    <hr>

    <p><%= @wiki.markdown_body %></p>
    
  </div>
  <div class="col-md-3 col-sm-3 col-xs-3 ">
    <br/>
    <div class="list-group">
      <% if policy(@wiki).edit? %>
        <%= link_to "Edit", edit_wiki_path(@wiki), class: 'list-group-item' %>
      <% end %>
      <% if policy(@wiki).destroy? %>
        <%= link_to "Delete", @wiki, method: :delete, class: 'list-group-item', data: { confirm: "Are you sure you want to delete this wiki?" } %>
      <% end %>
      
      <% if @wiki.private? %>
        <ul class="list-group-item no-bullets">
          <li><strong>Collaborators</strong></li><br/>

          <% @wiki.collaborators.each do |collaborator| %>
            <li class="<%= bold_if_current_user(collaborator) %>">
              <%= collaborator.name %>
            </li>
          <% end %>

        </ul>
      <% end %>
      
    </div>
  </div>
</div>