config/routes.rb
Rails.application.routes.draw do
  
  root to: 'welcome#index'
  get 'about' => 'welcome#about'
  
  resources :charges, only: [:new, :create]
  resources :wikis
  resources :collaborators
  
  get 'memberships/downgrade' => 'memberships#downgrade', as: :downgrade
  get '/transfer_owner', to: 'wikis#transfer_owner', as: :transfer_owner

  devise_for :users
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
</head>
<body>

  <div class="container">

    <!-- Nav -->
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      
      <!-- Sign in/out/up -->
      <div class="pull-right user-info sign-in-nudge">
        <small>
        <% if current_user %>
          <%= link_to current_user.name, edit_user_registration_path %> | 
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %></button>
        <% else %>
          <%= link_to "Sign in", new_user_session_path %> | 
          <%= link_to "Sign up", new_user_registration_path %>
        <% end %>
        </small>
      </div>

    </ul>

  
    <!-- display flash messages -->
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

  
    <%= yield %>
  
  </div>

</body>
</html>